Select  *
        From   ENTIDADES E
        WHERE E.IDENTIDAD='{196A1396-3CB1-463D-96B6-89FB275B4D01}  ';
       
     SELECT * 
        FROM DOCUMENTOS D
       WHERE D.DSREFERENCIA LIKE '%96007739%'
         AND D.DTDOCUMENTO>'01/02/2020';
        
       SELECT DM.* FROM DOCUMENTOS D,
                     MOVMATERIALES M,
                     DETALLEMOVMATERIALES@TR DM
       WHERE D.CDPUNTOVENTA='01431'
         AND D.SQCOMPROBANTE=28416
         AND D.IDMOVMATERIALES = M.IDMOVMATERIALES
         AND M.IDMOVMATERIALES = DM.IDMOVMATERIALES
         AND D.DTDOCUMENTO>'01/07/2020';
       ;
         SELECT * FROM MOVMATERIALES DM
         WHERE DM.IDDOCTRX='AAAABB3AE7D044B8E053100000D06587        ';
         
         SELECT * FROM DETALLEMOVMATERIALES
      
        
        SELECT * FROM PERSONAS P
        WHERE P.NUDOCUMENTO LIKE '%96007739%';
